---
name: checkpatch

on:
  pull_request:

jobs:
  checkpatch:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python venv
        uses: actions/prepare-venv@v1

      - name: Install Python dependencies
        run: pip install pyyaml==6.0.1 requests # Current version in noble

      - name: Show Versions
        run: |
          cat /etc/os-release
          python3 --version
          pip3 list

      - name: Check commits
        uses: actions/ubuntu-check-commit@main
